### ISSUE TITLE
Interpretation of "complete (pseudogene)" in nlr.txt output

### ISSUE THREAD

**Issue by dosshra** [steuernb/NLR-Annotator#17]
Hello
I wonder about the Interpretation of "complete (pseudogene)" in nlr.txt output.
I understand that the gene have all the essential  NLR motifs. 
How the NLR annotator detects that this gene is a pseudogene?
Thank you

**Comment by steuernb** [comment]
Hi,
The NLR-Annotator works on genomic sequence, thus we cannot predict proper intron/exon structure. Therefore, it is difficult to tell if a locus associated with NLR is a functional gene or not. The annotation process will translate DNA sequence to amino acids in all 6 reading frames and amino acid motifs are searched for in the translated sequence. Based on those motifs, we make the call. If we find a stop codon in one of those motifs we predict the (pseudogene). I am not entirely sure if this is really useful. Many of the normal "complete" loci are also pseudogenes but we cannot tell. Some of the (pseudogene) annotated are false calls. I thought in those rare cases where I have a chance to make a guess I might as well include it. Since we are talking about that column please also bare in mind that the differenciation complete/partial does not have any implication on function. Partial only means diversion from the canonical set of motifs.
