### ISSUE TITLE
Benchmarking and performance optimization

### ISSUE THREAD

**Issue by soungalo** [steuernb/NLR-Annotator#18]
Hello,
I'd like to know whether you can provide any benchmark information on performance and run times. For example, how long did it take you to run the pipeline on the A. thaliana and wheat genomes? How many CPUs did you use?
More importantly, can you advise on optimization of performance in terms of the number of chunks to which the genome should be chopped by ChopSequence.jar and the -t and -n options of NLR-Parser.jar? I'm not sure I understand how these actually work. E.g., if I have a workstation with 192 CPUs, what values would you recommend?
Thanks!

**Comment by steuernb** [comment]
Hi,
sorry, I never found this one a time-limiting step in comparison to other analyses. I just had a quick run for the Arabidopsis genome. Chopping the sequence takes less than a minute. I ran the NLR-Parser step with 8 cores and -t 7. The temporary output was written to an SSD. That took ~3 minutes. 

I use 8 cores and -t 7 for NLR-Parser. The one additional core for the java garbage collector, though I am not sure if that is really necessary. 

For every annotation, I will chop the genome into 20 kb fragments that overlap by 5 kb. You want to make sure that an NLR locus ends up on a single fragment. I don't think I miss many with those settings. 

NLR-Annotator currently uses MAST as motif search engine. Most of the settings are there to force MAST into the bevaviour I need. If you choose too large fragments (e.g. a whole chromosome) MAST will not cope. The -t parameter controls how many times MAST is called in parallel. Each MAST call uses a single core. MAST uses statistics resulting in an e-value similar to BLAST, meaning the e-value depends on the number of input sequences. Since MAST has an e-value threshold for reporting results, too many input sesquences may cause NLRs to not be reported. The -n parameter controls how many sequences are used within one MAST call at a time. The -n 1000 works well. I don't think you need to change it. Definitely don't increase it significantly. 

I hope that helps. It would be nice to hear how it performs on your big machine with wheat.
All the best
Burkhard

**Comment by steuernb** [comment]
Just went through some old log files. I processed a wheat genome in ~4 hours using 16 cores.

**Comment by soungalo** [comment]
I am analyzing a barley genome (5 Gb), using default params and 180 CPUs. Took around 30 min to chop the genome, then around 8 hours for NLR-Parser. I suspect that using so many CPUs creates an I/O bottleneck, but that probably depends on the storage I/O capabilities.
BTW, I had to set -Xmx , otherwise it crashes on heap size, so you might want to add this to the documentation.

**Comment by soungalo** [comment]
NLR-Annotator.jar has been running for 16 hours (not finished yet). Does it make any sense or is it stuck? I don't see any files being written and nothing is printed to stdout/stderr. My input xml (output of NLR-Parser.jar) is ~12G large.

**Comment by steuernb** [comment]
Good point with the Xmx. 
I/O might play quite a role. I wrote temporary files to an SSD, that might make a difference as well. 

NLR-Annotator should run less than an hour. There is something wrong. 12 G does not make sense to me. Are you checking one of the public barley sequences so I can try? If that is too much information about your project, feel free to contact me via email and we only post a solution here.

Would you mind posting the commands for ChopSequence, NLR-Parser and NLR-Annotator that you use?

**Comment by soungalo** [comment]
```
$ wget ftp://ftp.ensemblgenomes.org/pub/plants/release-49/fasta/hordeum_vulgare/dna/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa.gz
$ java -jar ChopSequence.jar -i Hordeum_vulgare.IBSC_v2.dna.toplevel.fa.gz -o Hordeum_vulgare.IBSC_v2.dna.toplevel.chop.fa
$ java -Xmx500g  -jar NLR-Parser.jar -i Hordeum_vulgare.IBSC_v2.dna.toplevel.chop.fa -x meme.xml -y <path>/bin/mast -c NLR.xml -t 180
$ java -Xmx500g  -jar NLR-Annotator.jar -i NLR.xml -o NLR.txt -g NLR.gff -b NLR.bed -m NLR_motifs.bed -a NLR_nb-arc.msa.fasta -f Hordeum_vulgare.IBSC_v2.dna.toplevel.fa.gz NLR.fasta 0
```

Is NLR-Annotator.jar supposed to print any messages when it starts running?

**Comment by steuernb** [comment]
Thanks! I'll give that a go and let you know.
Please run NLR-Parser with -t 16. I have never tested with as many cores as you have. That might be a source. Please try to run the NLR-Annotator without the -f option. 

What is the version of your meme installation? Can you also give it a try with the jar files from the github branch nlr-parser3, please?

**Comment by soungalo** [comment]
I reran, this time on the hard-masked version of the genome, using 30 CPUs (same parameters otherwise). NLR-Parser took around 2 hours and produced a 1.2G xml file. NLR-Annotator ran for another 2 hours.
Any idea how MAST (or other components) would work with a soft-masked genome?
I am using meme v4.8.1

**Comment by soungalo** [comment]
I am trying to run with jars from the NLR-Parser3 branch (installed MEME v5.1). But I'm getting the following error:
```
java -jar ChopSequence.jar
Error: Invalid or corrupt jarfile ChopSequence.jar
```
(and same for the two other jars).
Might be something about my java version - not sure how to check. I tried:
```
$ java  -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```
Any idea what's wrong?

**Comment by steuernb** [comment]
Not sure about the jar files. I have tested them. There were other people reporting corrupt jar files. I think the issue were security measurements by their institutes not allowing the jar files. If possible, try to download at home and test them there. If you consider that too risky, you can build from source.

**Comment by steuernb** [comment]
I ran the annotator on the barley genome. The xml file from the NLR-Parser had a size of 250 Mb. NLR-Annotator ran in less than a minute without -f.
Considering the massive differences in our xml outputs, is there something wrong with the settings on your server? If you have some computer with 8 Gb RAM, can you try running it on that?

below is the link to the barley output
[nlr.txt](https://github.com/steuernb/NLR-Annotator/files/5945466/nlr.txt)

**Comment by soungalo** [comment]
I managed to get the NLR-Parser3 jars to run by cloning the repo and switching to the nlr_parser3 branch. Using these jars, the whole process completed in ~2 hours, using 16 CPUs.
I still don't really understand the problem, but glad to have a solution.
Thanks for your help!
