### ISSUE TITLE
issues about NLR-Parser. Reason: Unrecognized option: -y

### ISSUE THREAD

**Issue by NingyuSUN** [steuernb/NLR-Annotator#19]
Hi,
I can use the chopsequence, but when I run the NLR-parser by using 
java -jar /Users/ningyu/Downloads/NLR-Parser.jar -y /Users/ningyu/meme/bin/mast -x /Users/ningyu/bin/meme.xml -i *.fasta -c output.nlr.xml, this comes out: 
Parsing failed.  Reason: Unrecognized option: -y
usage: java -jar NLR-Parser.jar -i mast.xml -o output.txt

I checked the NLR-parser and there is no such option, but in NLR annotator, you have -y and -x options. I think it's because I didn't install your scripts correctly but I am not very familiar with JAVA.

Thank you in advance!

**Comment by steuernb** [comment]
Hi,
The first NLR-Parser that was published did not have the option -y, because it just ran on the output files of MAST. Later versions call MAST directly, so you need to provide the MAST executable with -y. Please download the Parser and Annotator jar files from here: https://github.com/steuernb/NLR-Annotator/tree/nlr_parser3
Does this solve your problem?
all the best
Burkhard

**Comment by NingyuSUN** [comment]
Thank you! It's solved!
