### ISSUE TITLE
Questions about output format and downstream analysis

### ISSUE THREAD

**Issue by philippbayer** [steuernb/NLR-Annotator#2]
Hi! Thank you for this software.

I've run it now and got two questions:

1) How do you classify the output of NLR-Annotator into CNL, CN, TNL, etc.?
I've written a super ugly hardcoded Python script (here: https://gist.github.com/philippbayer/0052f5ad56121cd2252a1c5b90154ed1 ) which does the job based on motif combinations, but I wonder whether that's the right way, or whether there's an inbuilt way I don't know about

2) How would you get the 'complete' CDS/Protein sequences of the genes? Currently I'm thinking of extracting the hit regions using the -f flag, and then running AUGUSTUS there like BUSCO does it too, what do you think?

**Comment by steuernb** [comment]
Hi,
Thanks for using the software!

  1.  Motifs are the way to go here. The TNL would have the TIR motifs 18,15,13 and the CNL would have 17,16. In NLR-Parser, we also considered presence/absence of motif 6, which is only present in CNLs. But this leads to a lot of false positives if the motif6 is just below the threshold and gets omitted.
  2.  This one gives me a headache as well. The only reliable way so far is lots of rnaseq in combination with manual curation. Everything else I have tried so far comes with a lot of noise. It might be easier to try and find a surrogate for CDS to answer your question. For example, use only the NB-ARC associated motifs instead of the entire NB-ARC domain for phylogenetics. Please let me know if you find a better solution.
Cheers
Burkhard

**Comment by philippbayer** [comment]
Thank you for the fast answer - OK, so I made the right assumptions in 1), I see that 2) is messy as hell (when isn't genome annotation messy?? And especially in NLR genes where you have so many repetitive elements...), I will give it a try with augustus (maybe even the BRAKER pipeline) and keep you updated, probably reopening this issue then

(By the way, I apologise that I didn't cite NLR-Annotator as a possible solution in https://www.nature.com/articles/s41477-018-0264-0, as I didn't know about it back then -  I have rectified this in the upcoming accompanying poster at PAG!

**Comment by soungalo** [comment]
Hi @steuernb / @philippbayer, 
Just curious - have there been any "breakthroughs" on this since 2019?

**Comment by steuernb** [comment]
not from me. If you have money left over you could try targeted sequence capture (RenSeq) in combination with Pacbio Isoseq. That should do the job if you have a good genome sequence in the first place.

**Comment by soungalo** [comment]
Yes, I guess IsoSeq data could help, but due to the tight regulation and low expression of NLRs, this approach will probably require lots of data from various tissues and conditions.
I was thinking about training AUGUSTUS on known NLRs only (from the organism of interest) and trying to predict gene models on candidate sequences produced by NLR-Annotator. Do you think this could work?

**Comment by philippbayer** [comment]
There's at least one new tool I haven't tried: https://www.biorxiv.org/content/10.1101/2020.07.08.193961v2

I've had some good success by comparing the NLR-Annotator output with my own BRAKER/MAKER-based annotation using bedtools intersect

**Comment by soungalo** [comment]
Thanks for the link - I might give it a go.
Can you please explain what you mean by "comparing the NLR-Annotator output with my own BRAKER/MAKER-based annotation using bedtools intersect" ?
Is this just a validation to see how well MAKER detects NLRs, or do you actually use the NLR-Annotator output somehow?

**Comment by philippbayer** [comment]
I use the NLR annotator output! 
Here's an example with rice.  You can tell NLR-Annotator to give you the output in bed, here's the txt output instead:

<pre>
unaln_JG9       unaln_JG9_nlr_8 complete        4996421 4999151 +       17,16,1,6,4,5,3,12,2,8,7,9,9,11,9,19,11,11,11
unaln_JG9       unaln_JG9_nlr_9 partial 5075818 5076922 +       4,5,10,3,12,2,8,7,9,9,9
</pre>

So there's a complete NLR gene in from 4,996,421 to 49,99,151 on unaln_JG9. From there I run `bedtools intersect` with my MAKER gff of gene models to see whether MAKER has predicted a gene there. Did RGAugury output also find a gene there? What interproscan domains does that gene have? etc.

**Comment by soungalo** [comment]
Thanks. I'll try some of these approaches and see what works.
