### ISSUE TITLE
NLR-PARSER RUNS FOREVER!!!!

### ISSUE THREAD

**Issue by ank-man** [steuernb/NLR-Annotator#21]
After chopping the sequence I used the nlr-parser2.jar, but it runs forever with no output. I am attaching a screenshot 
![nlr-parser3](https://user-images.githubusercontent.com/64264081/122217666-4074a000-cecb-11eb-987a-25ee893f6bc7.png)

**Comment by steuernb** [comment]
Hi
My first wild guess is that you need to check the -x parameter. You need to provide the meme.xml with it. The argument looks a bit odd. It should be something like /path/to/meme.xml. If I see that correctly in your screenshot, your argument for -x does not end with meme.xml. Additionally, you seem to have a white space in the path, which will cause problems on most systems.
Please let me know if that solves your problem. 
all the best
Burkhard

**Comment by ank-man** [comment]
Hello, Thankyou for replying to this is the error I am getting.
java -jar NLR-Parser3.jar -t 15 -y /home/mittal/bin/mast -x meme.xml  -i
out.fasta -c output.nlr.xml
Exception in thread "main" java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at
org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
at nlr_parser.NLRParser.main(NLRParser.java:137)
... 5 more

Ankush

**Comment by steuernb** [comment]
Hi, can you please use the fasta file here (https://github.com/steuernb/NLR-Annotator/blob/nlr_parser3/Rgenes.CDS.fasta) instead of your out.fasta, to see if the rest is working? If this one runs through, please check the out.fasta in a text editor and see if there is something odd happening. An empty sequence or special symbols you do not expect in a fasta file. 

The other thing to try is running MAST on its own. You need to download some NLR protein from NCBI and run /home/mittal/bin/mast meme.xml mytestprotein.fasta

If that runs through I would be out of ideas without looking at your input data. 

cheers
Burkhard
